[package]
name = "mcmerge"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mcmerge"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
lopdf = "0.35"
anyhow = "1.0"
regex = "1.11"
walkdir = "2.5"
dialoguer = "0.11"
indicatif = "0.17"
