[workspace]
members = [
    "collect-cli",
    "collect-core",
    "src-tauri",
]
default-members = ["collect-cli"]
resolver = "2"

[workspace.dependencies]
reqwest = { version = "0.12.13", features = ["cookies", "gzip"] }
anyhow = "1.0.97"
tokio = { version = "1.37.0", features = ["rt", "net", "macros", "rt-multi-thread"] }
futures = "0.3.31"
rayon = "1.10.0"
bitflags = "2.9.0"
thiserror = "2.0"
