[workspace]
members = [
    "collect-cli",
    "collect-core",
]

[workspace.dependencies]
reqwest = { version = "0.12.4", features = ["cookies", "gzip"] }
anyhow = "1.0.84"
tokio = { version = "1.37.0", features = ["rt", "net", "macros", "rt-multi-thread"] }
