[package]
name = "collect-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.84"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["cookies", "gzip"] }
scraper = "0.19.0"
tokio = { version = "1.37.0", features = ["rt", "net", "macros"] }
