[package]
name = "collect-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.84"
base64 = "0.22.1"
futures = "0.3.30"
lol_html = "1.2.1"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["cookies", "gzip"] }
scraper = "0.19.0"
tokio = { version = "1.37.0", features = ["rt", "net", "macros"] }
unicode_escape = "0.1.0"
