[package]
name = "collect-core"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
base64 = "0.22.1"
futures = "0.3.30"
lol_html = "1.2.1"
regex = "1.10.4"
scraper = "0.19.0"
unicode_escape = "0.1.0"
