name: pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  release:
    types: [published]

jobs:
  artifact:
    if: startsWith(github.event.release.tag_name, 'app-v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Release Assets
        id: download
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.event.release.tag_name }}
          fileName: "*.json"
          out-file-path: "out"

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
