name: "publish-cli"
on:
  push:
    tags:
      - "cli-v*"

env:
  PROJECT_NAME: collect-cli

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - name: macos-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - name: macos-arm64
            runner: macos-latest
            target: aarch64-apple-darwin

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Dependencies (ubuntu only)
        if: matrix.runner == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libdbus-1-dev pkg-config

      - name: Build
        run: cargo build --verbose --locked --release --target ${{ matrix.target }} -p ${{ env.PROJECT_NAME }}

      - name: Bin Suffix
        shell: bash
        id: bin_suffix
        run: |
          case ${{ matrix.target }} in
            *-windows-*) SUFFIX=".exe" ;;
            *) SUFFIX="" ;;
          esac
          echo "SUFFIX=$SUFFIX" >> $GITHUB_OUTPUT

      - name: Rename Bin
        shell: bash
        run: |
          mv target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}${{ steps.bin_suffix.outputs.SUFFIX }} \
          target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ matrix.name }}${{ steps.bin_suffix.outputs.SUFFIX }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/${{ matrix.target }}/release/${{ env.PROJECT_NAME }}-${{ matrix.name }}${{ steps.bin_suffix.outputs.SUFFIX }}
          draft: true
